### ISSUE TITLE
EASY_END_BLOCK doesn't support function syntax

### ISSUE THREAD

**Issue by mmallet-youilabs** [yse/easy_profiler#139]
Currently, `EASY_END_BLOCK` calls cannot use function syntax. For example the following fails to compile:

```
EASY_BLOCK("Foo");
Foo();
EASY_END_BLOCK();
```
![image](https://user-images.githubusercontent.com/6910124/49110181-c459d480-f25a-11e8-880a-8138cd76f1a8.png)

Currently, the following is required instead:
```
EASY_BLOCK("Foo");
Foo();
EASY_END_BLOCK;
```

This differs from other macros such as `EASY_FUNCTION();` which allows being called with empty parenthesis. For ease of use, `EASY_END_BLOCK` should support being called with empty parenthesis.

**Comment by cas4ey** [comment]
Hi @mmallet-youilabs

The macro `EASY_FUNCTION()` has parenthesis because it has optional input args.  
`EASY_END_BLOCK` does not since it has no input args at all.  

However, it is not very good idea to change API which is currently in use. We can add new macro with parenthesis, but I think it would be better if you will do it on your own by defining/redefing this macro for your project individually.

**Comment by mmallet-youilabs** [comment]
That’s fair :) I didn’t know if it was possible to support parenthesis and no parenthesis at the same time.
