### ISSUE TITLE
Create, begin, end, store blocks manually

### ISSUE THREAD

**Issue by facontidavide** [yse/easy_profiler#29]
Hi,

thanks for your awesome tool.
I love it so much that I am planning to (ab)using it in a slightly different way.
I would like to measure the execution of tasks and not just functions/methods.

Ideally I need to be able to manually do the following operations:

1) Create a profile::Block
2) Start() it manually. 
3) Call manually finish()

In other words, I don't want the ProfilerManager to take care of this for me, but, on the other hand, ProfilerManager is the one that provides the socket interface and dump to file.

I am positive that what I described can be done, but it would be nice if you can give any hint

Regards

Davide

**Comment by cas4ey** [comment]
Hi,

Please, correct me if I'm wrong.

As I get you right - you want to profile some third-party library with it's own worker threads inside, but you have no access to this library source code (or maybe this is not c++ library)?
You are creating tasks in your application and then you are putting these tasks into third-party library thread pool, right? And at the same time these tasks have no c++ body in which you could put EASY_BLOCKs (these must be some scripts or something like that)?
In this case it is quite normal to have the situation like this:
`Task1.begin, Task2.begin, Task1.end, Task2.end`
And all happened in one thread which handles​ `begin` and `end` events.
Later (maybe tomorrow) I would add a picture to illustrate what I'm trying to say :)

If I'm right this conflicts with call-stack model (when Task2 must finish before Task1 would be finished). Technically this is quite easy for easy_profiler_core to store such information, but currently it is bad situation for profiler_gui because it was built for reading and displaying a call-stack of blocks. I would not say that it is impossible, but it requires a serious workaround.

**Comment by cas4ey** [comment]
But if I'm wrong and you are still planning to save and read a call-stack
`Task1.begin, Task2.begin, Task2.end, Task1.end`
then it would be quite easy to implement.

**Comment by yse** [comment]
Hi, Davide.
Thanks for the good feedback and the suggestion!
I've made a branch with the example of desired operations. This required a some minor changes in interface. So look at example: https://github.com/yse/easy_profiler/blob/feat/manage_custom_block/sample/custom_block/main.cpp
There is new interface function: `profiler::storeBlockDirectly(profiler::Block*)`. Some private functions of `Block` became public! (such as `start`, `finish` etc.)

**Comment by cas4ey** [comment]
By the way, maybe your problem is not a problem at all :)
If you has lots of tasks which makes it hard to put `EASY_BLOCK` in every task body but  each task has it's own name then you can just wrap your tasks with `EASY_BLOCK` using this task-name. As a result in profiler_gui you will see different blocks for each task with different name.
```cpp
class Task1 {
public:
    const char* name() const;
    void prepare();
    void execute();
    void finish();
};

class Task2 {
public:
    const char* name() const;
    void prepare();
    void execute();
    void finish();
};

class TaskPool {
public:
    void executeTasks() {
        for (auto& task : m_tasks) {
            EASY_BLOCK(task->name()); // Different block for each different task
            task->prepare();
            task->execute();
            task->finish();
        }
    }
};
```

**Comment by facontidavide** [comment]
@yse your example answer my question. 
On the other hand, I have the feeling that an easy trick would be to wrap the block inside a shared_ptr or unique_ptr to have more control about when the destructor (and the method finish()) is called.

What do you think?

**Comment by cas4ey** [comment]
@facontidavide , can you please give a couple of examples of such use case (including explicit start stop)? Current functionality already does start on constructor and stop on destructor. You can make Block a member of an object you want to profile, using shared/unique ptr also would let you control about when Block will be stopped.
But why you need an explicit start/stop functions then?

And please remember that current reader and viewer assumes **last-in first-out** model so it could be a huge mess in the viewer.

Please give an examples of the way(s) you want to use such functionality.

**Comment by rokups** [comment]
In my usecase it would be something like this:

```cpp
void Context::BeginSendEvent(Object* sender, StringHash eventType)
{
#ifdef ATOMIC_PROFILING
    profiler::begin(eventType.ToString());
#endif

    eventSenders_.Push(sender);
}

void Context::EndSendEvent()
{
    eventSenders_.Pop();

#ifdef ATOMIC_PROFILING
    profiler::end(eventType.ToString());
#endif
}
```

As a workaround i am adding profiler block one level up in the callstack where `BeginSendEvent()` and `EndSendEvent()` are called. In my case workaround is simple but i guess there can be other cases where it is not as easy to solve. For example when closed source lib calls begin/end events as callbacks.

**Comment by cas4ey** [comment]
@rokups , ok, you are talking about non-scoped blocks. Currently you can make `profiler::Block` a member of a class - this would allow you to begin and end block explicitly without changing API.

The things could be easy if we would add some kind of `profiler::beginBlockExplicit()` function to API which is slightly differ from what @yse has done in example.

This still rely on "last-in first-out" model and it could potentially lead to mistakes if `EndSendEvent()` would not be called and you have to take it into account.

**Comment by cas4ey** [comment]
Done
