### ISSUE TITLE
Profiling arbitrary values

### ISSUE THREAD

**Issue by rokups** [yse/easy_profiler#31]
Would it be possible to keep track of arbitrary float/integer values? That would be useful for engine to track object counts. It could be represented simply as FPS graph. API could be something like `profiler::sample(valueType, value)`.

Unrelated: we would love to track object lifetimes as well, however i have no idea how that could be presented in UI. Just something to think about.

**Comment by cas4ey** [comment]
We have already discussed with @yse the possibility to attach an integer value to `profiler::Block` (e.g. objects count) which could be used for algorithm complexity calculation, but we still have not decided how to do this in optimal way.

Or you talking about some global thread-local values (like max/avg frame duration)?

As for tracking object lifetimes: currently you can create `EASY_EVENT` - this is instant marker (`profiler::Block` which has no duration) and is displayed in GUI at the bottom of each thread below all blocks (check for `Settings -> View -> Draw event markers` in GUI). Using this together with dynamically generated name (you can use name generated at runtime - each block or event with different name would be considered as different blocks by GUI) will help you to track different objects create/destroy events.

**Comment by rokups** [comment]
> Or you talking about some global thread-local values (like max/avg frame duration)?

I am talking about arbitrary values where we could have unknown amount of them. Attaching value to a block could work but if we need to keep track of more than one value it could get weird. For instance js object count, c# object count, active physics bodies count etc etc..

Thanks on the tip for using events - will try that.

**Comment by cas4ey** [comment]
If you just want to inspect these values in GUI I think we can slightly modify `EASY_EVENT` to let it convert automatically value to string and use it as postfix for name.
For example:
```cpp
m_objectsCount = 520;
EASY_EVENT("Objects count =", EASY_VALUE(m_objectsCount));
```
will create event with name "Objects count = 520".
Or just use semantic of standard `printf()` function.
We can do this for `EASY_BLOCK` also.

You can test it right now:
```cpp
void MyClass::foo() {
    char name[128] = {};
    sprintf(name, "%s // Objects count = %u", __func__, m_objectsCount);
    EASY_BLOCK(name);
    // function body
}
```

By the way, side effect of such usage will be possibility to observe all blocks with the same objects count, because GUI treats same blocks with different names as different blocks.

Is that acceptible or you has another suggestion of using these values in GUI?

**Comment by rokups** [comment]
This would be more of a workaround than a solution right? I imagine it somewhat similar to current FPS graph. Seeing ups and downs of these values would be useful.

**Comment by cas4ey** [comment]
Yes, workaround, but you could use it right now :)

I'm not clear with displaying a graph similar to current FPS Monitor graph... Can you please give a bit more details?

Let's consider next example situation:
There is `Block1` with one `float` and one `int` values.
This block shoots 100 times per frame, and we have collected 300 frames.
I'm selecting this block in GUI, I can easily inspect current selected block attached values. But what's next?
Do I need to select one of those two values (`float` or `int`) to see a graph per frame or per thread (like current histogram)? How do you feel more comfortable to inspect these values?

**Comment by rokups** [comment]
Histogram would work for viewing one value.

How about a graph (just like FPS graph now) which draws as many differently colored lines as there are profiled values? Something like:

![](http://dryuc24b85zbr.cloudfront.net/tes/resources/6061038/image?width=500&height=500&version=1431118426034)

**Comment by cas4ey** [comment]
Hm, good point. But in that case these values have to be equal-order values to see reasonable graphs.
I think it would be nice to have a possibility to select which values you want to see on a graph (for example put a check-box near each attached value).

**Comment by cas4ey** [comment]
Bad news: we do not have much time to delevop new features so it would take longer than expected 😞

**Comment by rokups** [comment]
By the way i stumbled upon [microprofile](https://github.com/jonasmr/microprofile) that implements this as "counters". Might be something to draw inspiration from.

**Comment by cas4ey** [comment]
@rokups Thanks for the link!
Me and @yse had some ideas about implementation and think we could continue to work on it soon (but in slow pace 😃 )

**Comment by cas4ey** [comment]
Working on it :hammer:

**Comment by cas4ey** [comment]
Current progress:
![easyprofiler_arbitraryvaluesviewer](https://user-images.githubusercontent.com/10530007/35395718-3c5dbd66-01fc-11e8-9df9-612145a45e0a.png)

**Comment by rokups** [comment]
Looking great 👍 :)

**Comment by cas4ey** [comment]
Merged to develop 😀

**Comment by rokups** [comment]
hey @cas4ey i finally got around to checking latest code on develop branch. Could you give an example how to do value profiling? I do not see anything suggestive in `profiler.h` or profiler UI.

**Comment by cas4ey** [comment]
Hi @rokups 

You should see [<easy/arbitrary_value.h>](https://github.com/yse/easy_profiler/blob/develop/easy_profiler_core/include/easy/arbitrary_value.h) instead of `profiler.h`

See also profiler_sample:
* [prepareMath()](https://github.com/yse/easy_profiler/blob/develop/sample/main.cpp#L50);
* [calcSubbrain()](https://github.com/yse/easy_profiler/blob/develop/sample/main.cpp#L86);
* [quadratic_loop()](https://github.com/yse/easy_profiler/blob/develop/sample/main.cpp#L142);
* [modellingThread()](https://github.com/yse/easy_profiler/blob/develop/sample/main.cpp#L189);

_Notice: profiler_sample currently has an infinite execution time, so you should connect to it with profiler_gui to get profiling data._

Brief:
`EASY_VALUE(name, var, [color], [EASY_VIN(unique_id)]);`
* Optional arguments are marked with square brackets: `[color]`;
* `name` - value name _// currently only compile time names are supported_.
* `var` - variable or constant of simple scalar type or an array (which size is known at compile time).
  * If no `EASY_VIN(unique_id)` specified then the address of the `var` == `&var` would be used as it's `unique_id`;
  * You should pass `EASY_VIN(unique_id)` explicitly if `var` is a temporary object;
  * For dynamic arrays you should use `EASY_ARRAY` with explicitly specified `size`;
  * For text you should use `EASY_TEXT` or `EASY_STRING` (with explicitly specified `size`).
* `color` - color of this value displayed in the UI. [optional]
* `EASY_VIN(unique_id)` - unique id of the value. [optional]
  * Mainly used for saving compile time constants or values which could be changed from several places in code;
  * For global values `EASY_GLOBAL_VIN` can be used, which is forcing UI to use value **name** as it's unique_id;
  * In general there is no need of using `EASY_VIN` explicitly, it can be used for special cases.

For more information see `easy/arbitrary_value.h`.

**Comment by cas4ey** [comment]
We should add it to [Wiki](https://github.com/yse/easy_profiler/wiki)... :-)
By the way, do you have writing access for the Wiki? Any help with documentation is highly appreciated! :smile:

**Comment by rokups** [comment]
I do not. Please grant me access :+1:

**Comment by cas4ey** [comment]
I don't know how to do this :disappointed: 
But still there is a possibility to clone wiki repo [Wiki](https://github.com/yse/easy_profiler/wiki) page.
Maybe you can commit to a branch and we could merge it like a PR... :thinking:

**Comment by yse** [comment]
@rokups you are granted to make wiki changes =) I've removed restriction. You help will be very useful!
