### ISSUE TITLE
Memory Leaking

### ISSUE THREAD

**Issue by OriginalDecode** [yse/easy_profiler#43]
I've just started to add some blocks into my code, and I currently have the following function which runs fine, no leaking memory.
```
void Renderer::RenderLines()
{
#ifdef _PROFILE
	EASY_FUNCTION(profiler::colors::Amber);
#endif

	m_API->SetBlendState(eBlendStates::NO_BLEND);
	m_API->SetRasterizer(eRasterizer::CULL_NONE);

	ID3D11RenderTargetView* backbuffer = m_API->GetBackbuffer();
	ID3D11DepthStencilView* depth = m_DeferredRenderer->GetDepthStencil()->GetDepthView();
	m_API->GetContext()->OMSetRenderTargets(1, &backbuffer, depth);

	const auto commands = mySynchronizer->GetRenderCommands(eBufferType::LINE_BUFFER);
#ifdef _PROFILE
	EASY_BLOCK("LineCommand", profiler::colors::Red);
#endif
	for (s32 i = 0; i < commands.Size(); i++)
	{
		auto command = reinterpret_cast<LineCommand*>(commands[i]);
		m_API->SetDepthStencilState(command->m_ZEnabled ? eDepthStencilState::Z_ENABLED : eDepthStencilState::Z_DISABLED, 1);
		m_Line->Update(command->m_Points[0], command->m_Points[1]);
		m_Line->Render(m_Camera->GetOrientation(), m_Camera->GetPerspective());
	}
#ifdef _PROFILE
	EASY_END_BLOCK;
#endif

	m_API->SetBlendState(eBlendStates::NO_BLEND);
	m_API->SetDepthStencilState(eDepthStencilState::Z_ENABLED, 1);
	m_API->SetRasterizer(eRasterizer::CULL_BACK);
}
```
But when I add another block inside the already existing block, it can be EASY_BLOCK( foo ); or EASY_FUNCTION( bar ); both of them creates a memory leak in my application. 
```
#ifdef _PROFILE
	EASY_BLOCK("LineCommand", profiler::colors::Red);
#endif
	for (s32 i = 0; i < commands.Size(); i++)
	{
#ifdef _PROFILE
                EASY_BLOCK("InsideLoop", profiler::colors::Green);
#endif
		auto command = reinterpret_cast<LineCommand*>(commands[i]);
		m_API->SetDepthStencilState(command->m_ZEnabled ? eDepthStencilState::Z_ENABLED : eDepthStencilState::Z_DISABLED, 1);
		m_Line->Update(command->m_Points[0], command->m_Points[1]);
		m_Line->Render(m_Camera->GetOrientation(), m_Camera->GetPerspective());
#ifdef _PROFILE
                 EASY_END_BLOCK; 
#endif	
        }
#ifdef _PROFILE
	EASY_END_BLOCK;
#endif
```
I tried putting a EASY_FUNCTION inside the Render function that m_Line calls to see if the memory leak persisted, it did. 
I've got a separate configuration for my profiler & release which are setup the same way, but the profiler build has the _PROFILE flag defined, I flipped it over to release to check that it was not my own code that was causing the leak, I can confirm that it was not my own code causing this leak.
Is this something you can reproduce or have I managed to compile the lib incorrectly?

EDIT: 
Forgot to mention that I can place a block AFTER the existing block and NOT leak memory.
EDIT 2: 
Seems as if the memory leaking is only when I place a EASY_BLOCK around a loop and then another EASY_BLOCK / EASY_FUNCTION inside of the loop in someway.

**Comment by cas4ey** [comment]
Hi, 
Thanks for reporting an issue.

Memory usage is increased continuously while profiling, because profiler collects blocks. But it should be freed after calling `profiler::dumpBlocksToFile()` or after sending them via network to GUI. Do you dump blocks to file or stream (using GUI)?

**Comment by OriginalDecode** [comment]
I realised that memory leaking is probably the wrong term to use as the api frees the used memory correctly upon exit, my apologies for using the term incorrectly.
In any case I am using the GUI and am not dumping to file but I can still see a continuous increase in memory usage while the application runs, going up to 2GB memory usage within 5 minutes. I will do some more investigation after work today.
I hope this information will suffice for now.

**Comment by cas4ey** [comment]
Sorry for the confusion, we need to create a tutorial...

If you plan to control profiler from **GUI** you should use `profiler::startListen()` instead of `EASY_PROFILER_ENABLE` in your main program. Profiling would be enabled when you press `Capture` button. When capturing you should press `Stop` button and profiling would be disabled, all profiled data would be sent to GUI and memory used by main application would be freed.

If you plan to control profiler **manually from your application** then you shoud use `EASY_PROFILER_ENABLE` when you want to start profiling and `EASY_PROFILER_DISABLE` when you want to stop profiling. After that you should use `profiler::dumpBlocksToFile()` to save all profiled data to file. After doing that, memory used by main application would be freed.
In that case if you are using `EASY_PROFILER_ENABLE` and there are no `EASY_PROFILER_DISABLE` or  `profiler::dumpBlocksToFile()` in your code then memory usage will continue to grow, because profiler will keep collecting blocks.

There is also a hint: if you want to profile your applicaiton initialization you can use `EASY_PROFILER_ENABLE` together with `profiler::startListen()` at startup. When you are connecting GUI to the application which is already profiling then GUI will immidiately show you a capturing dialog (just as if you clicked `Capture` button) in which you can stop profiling.

Small remark: a couple of megabytes may not be freed though because there is `std::vector` used for stacks and it would keep reserved memory alive.

**Comment by OriginalDecode** [comment]
That does explain quite a few things. For some reason I was under the impression that I had to use EASY_PROFILER_ENABLE to be able to use profiler::startListen(). 
The problem ended up being solved by simply removing the EASY_PROFILER_ENABLE & EASY_PROFILER_DISABLE. 
I'll go ahead and close this issue as it was a 'user fault' and not a problem with the API.
