### ISSUE TITLE
MinGW builds/binary compatibility

### ISSUE THREAD

**Issue by nyorain** [yse/easy_profiler#49]
Hey, this library/program looks quite promising but sadly, I was not able to use it though using mingw w64, gcc-7 and release v1.2.0.
To use mingw i built the library from source but when trying to record blocks using the program (which i downloaded from the same release since i don't have qt installed and am not sure how to get it to work with mingw) i always received the error 

```
Can not read profiled blocks
Reason:
Profiled blocks number == 0
```

When trying to dump the blocks to a file at the end of the program, the ```profiler::dumpBlocksToFile("file.prof");``` call seems to get stuck (everytime i checked with gdb the thread was in a std::this_thread::sleep_for call triggered by this call).

Not sure how you serialize the blocks, but may it require binary compatibility between the viewer program and the library? If so, is it possible to package mingw releases with the next release? Would be really awesome!

Otherwise, do you have any ideas how to fix this?
Thanks for any help.

**Comment by nyorain** [comment]
Sorry, was an issue on my side.
Everything works for me now (windows as well as linux).
Will not edit/delete the issue for though, for anyone stumbling over something similar in the future:
Make sure to close all blocks before calling dumpBlocksToFile. I'm pretty sure this was the problem here.
MinGW Binaries would probably still me nice but are not really needed anymore.

**Comment by cas4ey** [comment]
Hi, @nyorain !
Thank you for reporting the problem and for posting the solution.
You are almost right: `dumpBlocksTo...` functions falls into deadlock if there is opened block **in the same thread** of caller of a `dumpBlocksTo...` function.
I said "almost" because usually you do not have to worry about closing all blocks in all threads before calling `dumpBlocksTo...` function. This function waits until all opened blocks would be closed so other threads may continue to execute as usual (except the thread which is performing dumping).
This waiting behavior was added to make sure that only fully finished frames would be dumped.

I should to mention this speciality in readme or on wiki though.
Thanks again :-)
