### ISSUE TITLE
GUI output after profiling

### ISSUE THREAD

**Issue by abhi1212** [yse/easy_profiler#79]
Hello,
I am compiling my application using Cmake and setting the prefix path to easyprofile directory, after doing a make I get an object file which just gives me the terminal output, can someone please help me on how can I get GUI output.

**Comment by rationalcoder** [comment]
You will have to go into more detail. What do you mean by object file? Presumably an executable? What terminal output are you talking about? Are you connecting remotely from the GUI? Are you asking how to go from and application that writes a .prof file to one that uses the GUI?

**Comment by abhi1212** [comment]
Hello,
Thanks a lot for the reply, I am pretty new to easy profiler but find it extremely helpful. 
I used the code on the git link to test how easy profiler works, I hardly did any modifications to it.
`#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <easy/profiler.h>

int main() {

    EASY_PROFILER_ENABLE;
    
    // some code
    EASY_BLOCK("Calculating sum"); // Block with default color
    int sum = 0;
    for (int i = 0; i < 10; ++i) {
        EASY_BLOCK("Addition", profiler::colors::Red); // Scoped red block (no EASY_END_BLOCK needed)
        sum += i;
    }
    EASY_END_BLOCK; // This ends "Calculating sum" block

    EASY_BLOCK("Calculating multiplication", profiler::colors::Blue500); // Blue block
    int mul = 1;
    for (int i = 1; i < 11; ++i){
        mul *= i;
	std::cout<<mul<<" ";
	}
     profiler::dumpBlocksToFile("test_profile.prof");
     return 0;
    //EASY_END_BLOCK; // This is not needed because all blocks are ended on destructor when closing braces met
}`


This is taking forever to run on my machine, Is it supposed to take more than an hour?
As this was taking considerable amount of time I decided to profile an application which just prints Hello World, After doing cmake and make I got an executable which prints Hello world on the Linux terminal when I run it.
I also got a .prof file in my build directory, It cannot be opened using gedit, I tried using kcachegrind but with no luck, does the .prof file contain the gui output, if yes how are we supposed to open it?
Your help is much appreciated.

**Comment by abhi1212** [comment]
I even tried using Snakeviz, though I know it is generally used for python profiling, but it did not help.

**Comment by cas4ey** [comment]
Hi @abhi1212 

The reason your example is taking forever is that you have to close all blocks before dumping them. `profiler::dumpBlocksToFile`is waiting for all **opened** blocks to finish. So **in your example** you have to put `EASY_END_BLOCK;` just before `profiler::dumpBlocksToFile(...)`.

The reason you can't open .prof file with text editor or other profiler-viewers is that it has own binary format which is documented [here](https://github.com/yse/easy_profiler/wiki/.prof-file-format-v1.3.0).
We are working on [exporting/importing](https://github.com/yse/easy_profiler/issues/67) it to other formats. Until then, you should use **profiler_gui** to view .prof files or to connect to your application and to collect blocks via network.
profiler_gui binaries are included into every easy_profiler release. Additionally you can build it by yourself from the [source code](https://github.com/yse/easy_profiler/tree/develop/profiler_gui) (you would have to install Qt in such case).

**Comment by abhi1212** [comment]
Thanks a lot @cas4ey.
I am able to launch it but I cannot see anything on th Gui, It is blank, I tried to figure out with the View toolbar but it does not seem to help.
![image](https://user-images.githubusercontent.com/22337618/32711252-16f61444-c80c-11e7-97bc-840bc1f26c9e.png)
Your help is much appreciated.

**Comment by cas4ey** [comment]
Try to right-click on ToolBar empty area - you should see context menu in which you need to check Diagram, Hierarchy and FPS Monitor

**Comment by abhi1212** [comment]
Thanks a lot @cas4ey.
I am profiling an application using a single block, I am starting it when my main starts and as my code is a never ending one, I end my block in a function which is called when I press ctr+c.
The problem is that I cannot see the hierarchy, the main calls multiple functions, but I am not able to see the hierarchy and the FPS monitor.
My main aim is to find the time taken by each and every called function.
Your help is much appreciated.

**Comment by rationalcoder** [comment]
@abhi1212 The problem here is a simple misunderstanding of how the profiler works. First, closing a block when you forcefully terminate a program is not a good idea. Second, That block is only measuring the time it takes to run `main`. You have to insert a block everywhere that you want to time your code. That means that, since you want to profile all of your functions, you will need at least one `EASY_BLOCK` or `EASY_FUNCTION` at the top of each function. Refer to the Wiki page here for examples. A block isn't magic. All it is an object that stores the time that it is created at and the time at which it ends (has its destructor called or is manually ended with `EASY_END_BLOCK`).

**Comment by abhi1212** [comment]
@rationalcoder  Thanks a lot, I have a better understanding of using the easy profiler now.

**Comment by cas4ey** [comment]
@abhi1212 
Measuring `main()` duration with easy_profiler is bad idea because currently the profiler waits until top-level block in each active thread would be finished. So measuring `main()` duration will hung your application if you will dump blocks in main thread before `EASY_END_BLOCK;` is used.
To measure `main()` duration you can simply use `std::chrono` or `profiler::currentTime()` or put `EASY_EVENT` in at begin of `main()` and at the end of `main()` and use time-ruler in profiler_gui (mouse double-click).

As for measuring functions: as @rationalcoder said, you have to insert `EASY_FUNCTION` or `EASY_BLOCK` manually into every function/block of code you want to measure.
You can also use `EASY_FUNCTION(profiler::OFF)`/`EASY_BLOCK(name, profiler::OFF);` to insert disabled blocks and turn them on from gui later.

**Comment by abhi1212** [comment]
Hello @cas4ey, In my code I have some function call from the main functions and those functions are not present in the same file, what would be an ideal way to profile those functions?

**Comment by cas4ey** [comment]
If by "not present in the same file" you mean a third-party library which source code is not available for you, then there is only one solution - wrap those function calls with `EASY_BLOCK`.

You can do it in three ways:

```cpp
. . .
EASY_BLOCK("foo()");
foo();
EASY_END_BLOCK;
. . .
```

Wrap with braces
```cpp
. . .
{
    EASY_BLOCK("foo()");
    foo();
}
. . .
```

Create wrapper-function
```cpp
void foo_call()
{
    EASY_FUNCTION();
    foo();
}
```

But if you are also compiling the file with `foo()` implementation then you can just insert `EASY_FUNCTION();` into it.
